actually stop on errors

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,6 +24,9 @@ usage() {
   echo "       --thread-safe"
   echo "       --debug"
   echo "       --no-link"
+}
+
+long_help() {
   echo 
   echo "To build an Apache 2 module, you must use apxs from *both* apache 1.3 and 2:"
   echo "  $0 --apxs=/apache/2/apxs --apxs1=/apache/1.3/apxs "
@@ -42,7 +45,7 @@ usage() {
 }
 
 fail() { 
- echo ; echo "Error: $1" ; echo ; exit 
+ echo ; echo "Error: $1" ; echo ; exit 1
 }
 
 while test $# != 0
@@ -84,11 +87,11 @@ do
       ;;
     --help)
       usage
+      long_help
       exit
       ;;
     *)
-      echo "Unrecognized option " $conf_option
-      exit
+      fail "Unrecognized option " $conf_option
       ;;
   esac
 done
@@ -134,15 +137,15 @@ echo
 
 if [ ! -x "$APXS" ]
  then 
-  echo "Error: apxs path is not valid."  && usage && exit 1
+  fail "Error: apxs path is not valid."
 fi
 if [ ! -x "$APXS1" ]
  then
-   echo "Error: apxs1 path is not valid.  (Apache 1.3 apxs is also required)"
+   fail "Error: apxs1 path is not valid.  (Apache 1.3 apxs is also required)"
 fi
 if [ ! -x "$MYSQLCFG" ] 
  then
-  echo "Error: mysql_config path is not valid." && usage && exit 1
+  fail "Error: mysql_config path is not valid." 
 fi
 if [ -x "$APRCONFIG" ]
  then
