Support APR and APR-UTIL 1.3 in configure script: new --apuconfig option. Some debug output re. OpenSolaris.

diff --git a/r1.1/configure b/r1.1/configure
--- a/r1.1/configure
+++ b/r1.1/configure
@@ -21,8 +21,9 @@ usage() {
   echo "       --apxs=/path/to/apxs "
   echo 
   echo "Options:  "
-  echo "       --apxs1=/path/to/apache13/apxs"
   echo "       --aprconfig=/path/to/apr-config"
+  echo "       --apuconfig=/path/to/apu-config"
+  echo "       --apxs1=/path/to/apache13/apxs"
   echo "       --linkopt='DSO linker options'"
   echo "       --thread-safe"
   echo "       --debug"
@@ -37,6 +38,8 @@ long_help() {
   echo "Use: "
   echo  
   echo "    --aprconfig if your APR is installed outside of apache2."
+  echo
+  echo "    --apuconfig for apr-util installed outside of APR."
   echo
   echo "    --thread-safe if you have a thread-safe mysql client library."
   echo 
@@ -93,6 +96,10 @@ do
     --aprconfig)
       APRCONFIG=$conf_arg
       test -x $APRCONFIG || fail "Cannot execute $APRCONFIG"
+      ;;
+    --apuconfig)
+      APUCONFIG=$conf_arg
+      test -x $APUCONFIG || fail "Cannot execute $APUCONFIG"
       ;;
     --mysys)
       case "$conf_arg" in 
@@ -155,6 +162,7 @@ echo "    mysql_config = " $MYSQLCFG
 echo "    apxs         = " $APXS 
 [ -n "$APXS1" ]       && echo "    apxs 1.3 =     " $APXS1
 [ -n "$APRCONFIG" ]   && echo "    apr-config =   " $APRCONFIG
+[ -n "$APUCONFIG" ]   && echo "    apu-config =   " $APUCONFIG
 echo
 
 [ $LINK_MYSYS -eq 1 ] && echo "Linking with -lmysys and -lmystrings" && echo
@@ -169,9 +177,14 @@ if [ ! -x "$MYSQLCFG" ]
 fi
 if [ -x "$APRCONFIG" ]
  then
-  APRLD=`$APRCONFIG --ldflags`
   APRINC=`$APRCONFIG --includes`
 fi
+if [ -x "$APUCONFIG" ]
+ then
+  APRINC="$APRINC "`$APUCONFIG --includes`
+fi
+
+
 
 MY_INC=`$MYSQLCFG --include`
 MY_LIBS=`$MYSQLCFG $GET_LIBS`
